name: Hello World Workflow Root

on: 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo "Hello, World!"
